### ISSUE TITLE
Hamburger icon in top left is partially green, play button is greyed out

### ISSUE THREAD

**Issue by BraydenDean** [Elundris/Air-for-Steam#80] opened 2015-09-17 23:17 UTC
Tried using master and devel, both seem to have the issue. I'm using the latest Steam Beta.
![screenshot from 2015-09-17 16-16-53](https://cloud.githubusercontent.com/assets/14267273/9948402/98576884-5d57-11e5-8ac9-1b8ad2298d83.png)

**Comment by tajobe** [comment] 2015-09-18 01:19
Duplicate of #78

**Comment by Elundris** [comment] 2015-09-18 05:33
Commented on #78, should be fixed now.

**Closed by Elundris** 2015-09-18 05:33 UTC
Labels: fixed
