### ISSUE TITLE
Settings dialog for Interface has wrong offsets

### ISSUE THREAD

**Issue by vincent-t** [Elundris/Air-for-Steam#7] opened 2015-03-07 16:23 UTC
I hope you can fix this, also occures in the english version:

![bildschirmfoto_2015-03-07_17-17-39](https://cloud.githubusercontent.com/assets/959709/6542089/81e472ec-c4ee-11e4-8ad8-eeef658277ba.png)

**Comment by Elundris** [comment] 2015-03-08 03:30
Are you on OS X or Linux? If so, that might also be the cause of the problem since I don't have official support for multiple OS's at this point.

**Comment by vincent-t** [comment] 2015-03-08 09:17
Sorry i didn'n mention, i'm on linux.

**Comment by Elundris** [comment] 2015-03-08 14:17
This is on my to-do's now, but it definitely is going to fall lower on the priority list than things like getting a dark them implemented which is my current focus.

**Comment by vincent-t** [comment] 2015-03-08 16:43
Thank you and keep up the good work!

**Comment by vdrandom** [comment] 2015-04-07 18:34
It'd be awesome to get a one place to edit font sizes if possible, because font sizes on linux are off, at least with ubuntu font patches and editing all those files is going to be a nightmare (also good lord that amount of tabs in _fonts.styles). The bug mentioned in OP probably has something to do with the font size issue.
```
% grep -Rlsi font-size . 
./Friends/gameinvitebar.res
./Friends/broadcastinvitebar.res
./Friends/tradeinvitebar.res
./Friends/voicebar.res
./Friends/broadcastapprovebar.res
./Resource/layout/htmlfindbar.layout
./Resource/layout/broadcast_firsttime.layout
./Resource/layout/overlay_achievementsdetails.layout
./Resource/layout/overlaydesktop_lores.layout
./Resource/layout/overlay_screenshotspanel.layout
./Resource/layout/settingsdialog.layout
./Resource/layout/overlaydesktop.layout
./Resource/layout/htmlimebar.layout
./Resource/layout/overlay_communityhubpanel.layout
./Resource/layout/overlay_friendsdetails.layout
./Resource/layout/parentalunlockdialog.layout
./Resource/styles/_fonts.styles
```

**Comment by Elundris** [comment] 2015-04-07 21:53
Yeah, that was one of my big initiatives with the latest update. There are a few in that list that I legitimately missed (and I shall move them to _fonts momentarily). As for the rest, I haven't figured out how to get those to work properly out of an include file.

Ok, yeah, the tabs were a bit overkill... it was useful when I was building the file out, but not so much anymore. Just updated that!

**Comment by Elundris** [comment] 2015-04-15 21:14
@vincent-t Could you see if the latest changes on `develop` fix the overlap issues for you?

**Comment by thesbros** [comment] 2015-04-16 05:54
elementary OS Freya (Ubuntu 14.04) here, I was having this issue, checked out the develop branch and it's working.

**Comment by vincent-t** [comment] 2015-04-16 10:35
@Elundris Great work! The bug is mostly fixed. Only two issues left:

![bildschirmfoto_2015-04-16_12-29-35](https://cloud.githubusercontent.com/assets/959709/7179117/e4c9a08e-e434-11e4-86c7-04b8a90032ab.png)
![bildschirmfoto_2015-04-16_12-30-12](https://cloud.githubusercontent.com/assets/959709/7179116/e4c912cc-e434-11e4-8b46-fb5542925691.png)

Best regards,

vincent

**Comment by Elundris** [comment] 2015-04-16 15:56
That one looks to be font-size or family related. Is Roboto installed? Did you make any tweaks to font size, or are is rendering really that different on Linux?

Here's how mine looks on Windows:
![capture](https://cloud.githubusercontent.com/assets/8676168/7185224/50a25e8c-e416-11e4-8191-74e0567c338d.PNG)

**Comment by vincent-t** [comment] 2015-04-16 16:11
My bad, forgot to install roboto. Now everything is fine:
![bildschirmfoto_2015-04-16_18-09-07](https://cloud.githubusercontent.com/assets/959709/7185600/fdd4197c-e463-11e4-830b-ecd27254d41f.png)

**Comment by sebie** [comment] 2015-04-16 22:49
Closing the issue as it is fixed and available in the `develop` branch. If you have any further comments, questions or praises, feel free to leave them below.

Thank you for contributing to Air!

**Closed by sebie** 2015-04-16 22:49 UTC
Labels: bug, Fixed, Linux, To-do
